# Generated by Django 4.2.30 on 2026-09-12 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ESCROW_HELD', 'Funds Held in Escrow'), ('RELEASED', 'Released to Freelancer'), ('REFUNDED', 'Refunded to Client')], default='ESCROW_HELD', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='Escrow Deposit', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
