services:
  - type: web
    name: freelancify
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn freelancify.wsgi:application"

    envVars:
      - key: DEBUG
        value: "false"

      - key: SECRET_KEY
        generateValue: true